# Generated by Django 4.0.4 on 2022-08-23 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_disponibilite_week_of'),
    ]

    operations = [
        migrations.RenameField(
            model_name='disponibilite',
            old_name='week_of',
            new_name='_week_of',
        ),
    ]
