# Generated by Django 4.0.4 on 2022-08-23 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_rename_week_of_disponibilite__week_of'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='disponibilite',
            name='_week_of',
        ),
    ]
