# Generated by Django 4.0.4 on 2022-08-23 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0005_disponibilite__week_of'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schedule',
            old_name='semaine_de',
            new_name='_semaine_de',
        ),
        migrations.AlterField(
            model_name='schedule',
            name='_semaine_de',
            field=models.DateField(blank=True, db_column='semaine_de', null=True),
        ),
    ]
