# Generated by Django 4.0.4 on 2022-08-23 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0006_rename_semaine_de_schedule__semaine_de_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='_semaine_de',
            field=models.DateField(db_column='semaine_de', default='2022-01-01'),
        ),
    ]
