# Generated by Django 4.0.4 on 2022-11-15 23:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0008_remove_disponibilite__week_of_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('msg', models.CharField(max_length=255)),
                ('status', models.IntegerField(blank=True, default=0)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('formateur_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.formateur')),
            ],
        ),
    ]
